<?php
// All type post element
add_action('init', 'init_custom_allposttype',999);
if(!function_exists('init_custom_allposttype')){
    function init_custom_allposttype(){
        global $tw_pbItems;
        //Post Type
        $ignoredPostType=array('page','attachment','revision','nav_menu_item','options','tw_price','tw_partner','tw_team','product','product_variation','shop_order','shop_coupon','wpcf7_contact_form');
        $arrayPostType = array();
        $arrayPostTypeHide = array();
        $postTypeList = get_post_types(array(),'objects');
        foreach($postTypeList as $slug => $typeOptions){
            if(!in_array($slug, $ignoredPostType)){
                $arrayPostType[$slug] = $typeOptions->labels->menu_name;
                //---------hide----------
                $tmpArr=array();
                foreach($postTypeList as $slugSub => $typeOptionsSub){
                    if(!in_array($slugSub, $ignoredPostType)&&$slug!==$slugSub){$tmpArr[]='cat_'.$slugSub;}
                }
                $arrayPostTypeHide[$slug]=implode(",", $tmpArr);
            }
        }
        //All Type Catigories
        $arrayAllTypeCategories=array();
        foreach($arrayPostType as $slug => $name){
            $arrayAllTypeCategories[$slug]=array();
            $taxonomyNames = get_object_taxonomies($slug);
            if(isset($taxonomyNames[0])){
                $taxonomyCategories = get_terms($taxonomyNames[0], 'hide_empty=0');
                $arrayAllTypeCategories[$slug]["0"] = "Select Category";
                if(!empty($taxonomyCategories)) {
                    foreach ($taxonomyCategories as $taxonomyCategorie) {
                        $arrayAllTypeCategories[$slug][$taxonomyCategorie->slug] = $taxonomyCategorie->name;
                    }
                }
            }
        }
        //All Type Settings
        $allTypeSettings = array(
            "post_type" => array(
                "title"   => "Post Type",
                "type"    => "category",
                "options" => array_merge(array("0"=>"Select Category"),$arrayPostType),
//                "hide"    => $arrayPostTypeHide,
                "default" => "0",
                "desc"    => "If you want to display Specify Post Type then choose.",
            ),
            "post_type_slugs" => array(
                "type" => "hidden",
                "selector" => "post_type",
                "default" => "",
            ),
        );
        foreach($arrayPostType as $slug => $name){
            $allTypeSettings["cat_".$slug] = array(
                "title" => $name." category",
                "type" => "category",
                "options" => $arrayAllTypeCategories[$slug],
                "default" => "0",
                "desc" => "If you want to display Specify category then choose.",
            );
            $allTypeSettings["cat_".$slug."_slugs"] = array(
                "type" => "hidden",
                "selector" => "cat_".$slug,
                "default" => "",
            );
        }
        $tw_pbItems["all_post_type"] = array(
            "name" => "All post type",
            "size" => "size-1-3",
            "row-type" => "row",
            "min-size" => "size-1-3",
            "only" => "builder",
            "settings" => array_merge(
                $allTypeSettings,
                array(
                    "post_count" => array(
                        "title" => "Post Count",
                        "type" => "text",
                        "holder" => "10",
                        "default" => "10",
                        "desc" => "Insert how many posts will displayed in blog.",
                    ),
                    "layout" => array(
                        "title" => "Blog Layout",
                        "type" => "select",
                        "options" => array('standard'=>'Standard','2'=>'2 Columns','3'=>'3 Columns','4'=>'4 Columns'),
                        "default" => "standard",
                        "desc" => "",
                    ),
                    "pagination" => array(
                        "title" => "Display Pagination?",
                        "type" => "select",
                        "options" => array('none' => 'None', 'simple' => 'Simple pagination', 'infinite' => 'Infinite scroll'),
                        "default" => "none",
                        "desc" => "",
                    ),
                    "excerpt_count" => array(
                        "title" => "Excerpt Count",
                        "type" => "text",
                        "holder" => "50",
                        "default" => "50",
                        "desc" => "How much blog words displayed in blog Excerpt. Must insert Digits including 0.",
                    ),
                    "more_text" => array(
                        "title" => "Read more text",
                        "type" => "text",
                        "holder" => "",
                        "default" => "",
                        "desc" => "Insert custom 'Read More' text",
                    ),
                )
            ),
        );
    }
}
/////////////////////////////////////////////////////////////////////////////////
// Order
$order = array(
    "date_desc" => "Date Desc",
    "date_asc" => "Date Asc",
    "title_desc" => "Title Desc",
    "title_asc" => "Title Asc",    
    "random" => "Random",
);

$tw_pbRowSettings = array(
    "admin_row_name" => array(
        "title" => "Container Name",
        "type" => "text",
        "holder" => "",
        "default" => "No Named Layout",
        "desc" => "",
    ),
    "row_custom_class" => array(
        "title" => "Custom Class and ID",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "If you wanna enable ONE PAGE check our Knowledge Base center",
    ),
    "background_color" => array(
        "title" => "Background color",
        "type" => "color",
        "holder" => "",
        "default" => "",
        "desc" => "Choose background color.",
    ),
    "background_image" => array(
        "title" => "Background image",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "Upload background image.",
    ),
    "add_background_image" => array(
        "title" => "",
        "type" => "button",
        "save_to" => "background_image",
        "default" => "Upload",
        "desc" => "",
    ),
    "background_repeat" => array(
        "title" => "Background image repeat",
        "type" => "select",
        "options" => array("repeat"=>"repeat","no-repeat"=>"no-repeat","repeat-x"=>"repeat-x","repeat-y"=>"repeat-y"),
        "default" => "",
        "desc" => "Upload background image.",
    ),
    "background_position" => array(
        "title" => "Background image position",
        "type" => "select",
        "options" => $bgposition,
        "default" => "",
        "desc" => "Upload background image.",
    ),
    "background_attachment" => array(
        "title" => "Background image position",
        "type" => "select",
        "options" => array("scroll"=>"scroll", "fixed"=>"fixed"),
        "default" => "",
        "desc" => "Upload background image.",
    ),
    "background_prllx" => array(
        "title" => "Is Uploaded Background parallax?",
        "type" => "checkbox",
        "holder" => "",
        "default" => "",
        "desc" => "",
    ),
    "background_video" => array(
        "title" => "Background video url",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "",
    ),
    "add_background_video" => array(
        "title" => "",
        "type" => "button",
        "save_to" => "background_video",
        "default" => "Upload",
        "desc" => "",
    ),
    "padding_top" => array(
        "title" => "Container Padding Top",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "Controlling Container top margin value. Note: Insert only Digits, 0 means no space, Default is 60px;",
    ),
    "padding_bottom" => array(
        "title" => "Container Padding Bottom",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "Those options will helps you insert images with no space top or bottom from container.",
    ),
    
    
    
    
    "admin_row_closed" => array(
        "title" => "",
        "type" => "hidden",
        "holder" => "",
        "default" => "false",
        "desc" => "",
    ),
    "row_layout" => array(
        "title" => "",
        "type" => "hidden",
        "holder" => "",
        "default" => "full",
        "desc" => "",
    ),
    "row_contrast" => array(
        "title" => "Container Color Scheme",
        "type" => "select",
        "options" => array('dark' => 'Dark', 'light' => 'Light'),
        "default" => "light",
        "desc" => "",
    ),
);
$tw_pbHeadSettings = array(
    "item_title" => array(
        "title" => "Insert title here",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "Insert title here",
    ),
    "item_custom_class" => array(
        "title" => "Custom Class",
        "type" => "text",
        "holder" => "",
        "default" => "",
        "desc" => "",
    ),
    "item_animation" => array(
        "title" => "Animation",
        "type" => "select",
        "options" => $genAnimationArray,
        "default" => "none",
        "desc" => "Animation.",
    ),
    "item_animation_delay" => array(
        "title" => "Animation delay",
        "type" => "text",
        "holder" => "Example:300",
        "default" => "",
        "desc" => "Animation Delay",
    ),
);
$tw_pbItems = array(
    "accordion" => array(
        "name" => "Accordion",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/accordion-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "accordion", "settings" => "items"),
                "default" => "Add Accordion",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "item_title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "",
                            "default" => "Accordion Title",
                            "desc" => "",
                        ),
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "color" => array(
                            "title" => "Color",
                            "type" => "color",
                            "holder" => "#2dcb73",
                            "default" => "#2dcb73",
                            "desc" => "Choose color.",
                        ),
                        "item_expand" => array(
                            "title" => "Expand item",
                            "type" => "checkbox",
                            "default" => "false",
                            "desc" => "Expand ?",
                        ),
                        "item_content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Completely synergize resource sucking relationships via premier niche markets.",
                            "default" => "Completely synergize resource sucking relationships via premier niche markets.",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "before_after" => array(
        "name" => "Before After",
        "size" => "size-1-3",
        "settings" => array(
            "before" => array(
                "title" => "Before Image",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "add_before" => array(
                "title" => "",
                "type" => "button",
                "save_to" => "before",
                "default" => "Upload",
                "desc" => "",
            ),
            "after" => array(
                "title" => "After Image",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "add_after" => array(
                "title" => "",
                "type" => "button",
                "save_to" => "after",
                "default" => "Upload",
                "desc" => "",
            ),
        ),
    ),
    "blog" => array(
        "name" => "Blog",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/blog/",
        "settings" => array(
            "category" => array(
                "title" => "Blog category",
                "type" => "category",
                "options" => $post_categories,
                "default" => "0",
                "desc" => "If you want to display Specify category then choose.",
            ),
            "category_ids" => array(
                "type" => "hidden",
                "selector" => "category",
                "default" => "",
            ),
            "post_count" => array(
                "title" => "Post Count",
                "type" => "text",
                "holder" => "10",
                "default" => "10",
                "desc" => "Insert how many posts will displayed in blog.",
            ),
            "layout" => array(
                "title" => "Blog Layout",
                "type" => "select",
                "options" => array('standard'=>'Standard','2'=>'2 Columns','3'=>'3 Columns','4'=>'4 Columns'),
                "default" => "standard",
                "desc" => "",
            ),
            "pagination" => array(
                "title" => "Display Pagination?",
                "type" => "select",
                "options" => array('none' => 'None', 'simple' => 'Simple pagination', 'infinite' => 'Infinite scroll'),
                "default" => "none",
                "desc" => "",
            ),
            "excerpt_count" => array(
                "title" => "Excerpt Count",
                "type" => "text",
                "holder" => "50",
                "default" => "50",
                "desc" => "How much blog words displayed in blog Excerpt. Must insert Digits including 0.",
            ),
            "more_text" => array(
                "title" => "Read more text",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Insert custom 'Read More' text",
            ),
        ),
    ),
    "button" => array(
        "name" => "Button",
        "only" => "shortcode", //builder
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title" => "Button Text",
                "type" => "text",
                "holder" => "Button",
                "default" => "Button",
                "desc" => "Insert your button text",
            ),
            "link" => array(
                "title" => "Button Link",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Insert button link URL",
            ),
            "size" => array(
                "title" => "Button Size",
                "type" => "select",
                "options" => array("small" => "Small", "medium" => "Medium", "large" => "Large"),
                "holder" => "",
                "default" => "medium",
                "desc" => "Choose button size",
            ),
            "rounded" => array(
                "title" => "Rounded",
                "type" => "checkbox",
                "default" => "false",
                "desc" => "",
            ),
            "style" => array(
                "title" => "Button Style",
                "type" => "select",
                "options" => array("flat" => "Flat", "border" => "Border"),
                "holder" => "",
                "default" => "flat",
                "desc" => "Choose button size",
            ),
            "hover" => array(
                "title" => "Hover Style",
                "type" => "select",
                "options" => array("default" => "default", "hover2" => "style 2", "hover3" => "style 3", "hover4" => "style 4", "hover5" => "style 5", "hover6" => "style 6"),
                "holder" => "",
                "default" => "nohover",
                "desc" => "Choose button hover effect",
            ),
            "color" => array(
                "title" => "Button Color",
                "type" => "color",
                "holder" => "",
                "default" => "",
                "desc" => "Choose color",
            ),
            "target" => array(
                "title" => "Button Target",
                "type" => "select",
                "options" => $linkTarget,
                "holder" => "",
                "default" => "_blank",
                "desc" => "Blank will open new window, self will current window",
            ),
        ),
    ),
    "callout" => array(
        "name" => "Callout",
        "size" => "size-1-1",
        "content" => "callout_text",
        "help" => "http://support.themewaves.com/knowledgebase/callout-element-tutorial/",
        "settings" => array(
            "callout_text" => array(
                "title" => "Callout Big Title",
                "type" => "textArea",
                "holder" => "",
                "default" => 'Lorem ipsum dolor sit amet, consectetuer adipiscing commodo ligula eget dolor?',
                "desc" => "",
            ),
            "description" => array(
                "title" => "Callout Description",
                "type" => "textArea",
                "holder" => "Edit this section for custom Callout Text",
                "default" => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deltias excepturi sint occaecati cupiditate non provident.',
                "desc" => "",
            ),
            "btn_text" => array(
                "title" => "",
                "type" => "text",
                "holder" => "button text",
                "default" => "Purchase Now",
                "desc" => "Custom 'Read More'",
            ),
            "btn_color" => array(
                "title" => "",
                "type" => "color",
                "holder" => "",
                "default" => "",
                "desc" => "Button background color",
            ),
            "btn_url" => array(
                "title" => "",
                "type" => "text",
                "holder" => "Only URL here",
                "default" => "#",
                "desc" => "Read More Link URL",
            ),
            "btn_target" => array(
                "title" => "",
                "type" => "select",
                "options" => $linkTarget,
                "default" => "_blank",
                "desc" => "Blank is opened new window. Self is opened current.",
            ),
        ),
    ),
    "chart_circle" => array(
        "name" => "Chart Circle",
        "size" => "size-1-3",
        "help" => "http://support.themewaves.com/knowledgebase/chart-circle-element-tutorial/",
        "settings" => array(
            "item_animation_delay" => array(
                "title" => "Animation delay",
                "type" => "text",
                "holder" => "Example:300",
                "default" => "",
                "desc" => "Animation Delay",
            ),
            "cc" => array(
                "title" => "Edit Chart",
                "type" => "cc",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "cc_type" => array(
                "title" => "Type",
                "type" => "select",
                "options" => array('text' => 'Text', 'fa' => 'Font Awesome'),
                "default" => "text",
                "desc" => "",
            ),
            "cc_line_width" => array(
                "title" => "Line Width",
                "type" => "hidden",
                "holder" => "",
                "default" => "6",
                "desc" => "",
            ),
            "cc_text" => array(
                "title" => "Text",
                "type" => "hidden",
                "holder" => "",
                "default" => "80%",
                "desc" => "",
            ),
            "cc_percent" => array(
                "title" => "Percent",
                "type" => "hidden",
                "holder" => "",
                "default" => "80",
                "desc" => "",
            ),
            "cc_size" => array(
                "title" => "Size",
                "type" => "hidden",
                "holder" => "",
                "default" => "100",
                "desc" => "",
            ),
            "cc_font_size" => array(
                "title" => "Font Size",
                "type" => "hidden",
                "holder" => "",
                "default" => "28",
                "desc" => "",
            ),
            "cc_font_color" => array(
                "title" => "Font Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "#2dcb73",
                "desc" => "",
            ),
            "cc_color" => array(
                "title" => "Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "#2dcb73",
                "desc" => "",
            ),
            "cc_track_color" => array(
                "title" => "Track Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "#f5f5f5",
                "desc" => "",
            ),
            "cc_icon" => array(
                "title" => "Icon",
                "type" => "hidden",
                "holder" => "",
                "default" => "fa-angellist",
                "desc" => "",
            ),
        ),
    ),
    "chart_graph" => array(
        "name" => "Chart Graph",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/chart-graph-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "chart_graph", "settings" => "items"),
                "default" => "Add Chart Item",
                "desc" => "",
            ),
            "item_animation_delay" => array(
                "title" => "Animation delay",
                "type" => "text",
                "holder" => "Example:300",
                "default" => "",
                "desc" => "Animation Delay",
            ),
            "item_height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "Example: Empty or 100px",
                "default" => "",
                "desc" => "",
            ),
            "type" => array(
                "title" => "Chart Type",
                "type" => "select",
                "options" => array('Line' => 'Line', 'Bar' => 'Bar', 'Radar' => 'Radar'),
                "default" => "Line",
                "desc" => "All chart types and more information <a href='http://www.chartjs.org/docs/' target='_blank'>here</a>.",
            ),
            "begin_at_zero" => array(
                "title" => "Begin At Zero",
                "type" => "checkbox",
                "default" => "false",
                "desc" => "Whether the scale should start at zero, or an order of magnitude down from the lowest value",
            ),
            "labels" => array(
                "title" => "",
                "type" => "text",
                "holder" => "",
                "default" => "January , February , March , April",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "datas",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "datas" => array(
                            "title" => "Datas",
                            "type" => "text",
                            "holder" => "",
                            "default" => "40,45,50,60",
                            "desc" => "Example: 40,45,50,60. Note: Digits only",
                        ),
                        "fill_color" => array(
                            "title" => "Fill Color",
                            "type" => "color",
                            "holder" => "#FF5744",
                            "default" => "#FF5744",
                            "desc" => "Fill Color",
                        ),
                        "fill_text" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "",
                            "default" => "",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "chart_pie" => array(
        "name" => "Chart Pie",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/chart-pie-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "chart_pie", "settings" => "items"),
                "default" => "Add Chart Item",
                "desc" => "",
            ),
            "item_animation_delay" => array(
                "title" => "Animation delay",
                "type" => "text",
                "holder" => "Example:300",
                "default" => "",
                "desc" => "Animation Delay",
            ),
            "type" => array(
                "title" => "Chart Type",
                "type" => "select",
                "options" => array( 'Doughnut' => 'Doughnut', 'PolarArea' => 'Polar Area', 'Pie' => 'Pie'),
                "default" => "Doughnut",
                "desc" => "All chart types and more information <a href='http://www.chartjs.org/docs/' target='_blank'>here</a>.",
            ),
            "begin_at_zero" => array(
                "title" => "Begin At Zero",
                "type" => "checkbox",
                "default" => "false",
                "desc" => "Whether the scale should start at zero, or an order of magnitude down from the lowest value",
            ),
            "label_list" => array(
                "title" => "Show Label Lists",
                "type" => "checkbox",
                "default" => "false",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "value",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "value" => array(
                            "title" => "100",
                            "type" => "text",
                            "holder" => "100",
                            "default" => "100",
                            "desc" => "Note: Only Digit",
                        ),
                        "color" => array(
                            "title" => "",
                            "type" => "color",
                            "holder" => "#2dcb73",
                            "default" => "#2dcb73",
                            "desc" => "Choose color",
                        ),
                        "fill_text" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "",
                            "default" => "",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "column" => array(
        "name" => "Column",
        "size" => "size-1-3",
        "content" => "column_content",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/column/",
        "settings" => array(
            "column_content" => array(
                "title" => "",
                "type" => "textArea",
                "tinyMCE" => "true",
                "holder" => "",
                "default" => "Column Content",
                "desc" => "",
            ),
        ),
    ),
    "sh_column" => array(
        "name" => "Column Shortcode",
        "size" => "size-1-3",
        "only" => "shortcode",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/column-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "sh_column", "settings" => "items"),
                "default" => "Add Column",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "column_size",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "column_size" => array(
                            "title" => "Choose Column Size",
                            "type" => "select",
                            "options" => array("1 / 6" => "1 / 6", "1 / 4" => "1 / 4", "1 / 3" => "1 / 3", "1 / 2" => "1 / 2", "2 / 3" => "2 / 3", "3 / 4" => "3 / 4", "1 / 1" => "1 / 1"),
                            "default" => "1 / 3",
                            "desc" => "",
                        ),
                        "column_content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Completely synergize resource sucking relationships via premier niche markets.",
                            "default" => "Completely synergize resource sucking relationships via premier niche markets.",
                            "desc" => ".",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "comingsoon" => array(
        "name" => "Coming Soon",
        "size" => "size-1-1",
        "min-size" => "size-1-2",
        "content" => "coming_content",
        "help" => "",
        "settings" => array(
            "coming_title" => array(
                "title" => "Title",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "coming_content" => array(
                "title" => "",
                "type" => "textArea",
                "tinyMCE" => "true",
                "holder" => "",
                "default" => "Coming Soon Content",
                "desc" => "",
            ),
            "coming_years" => array(
                "title" => "Years",
                "type" => "select",
                "options" => array("2013" => "2013", "2014" => "2014", "2015" => "2015", "2016" => "2016", "2017" => "2017", "2018" => "2018"),
                "holder" => "",
                "default" => "2018",
                "desc" => "",
            ),
            "coming_months" => array(
                "title" => "Months",
                "type" => "select",
                "options" => array("01" => "January","02" => "February","03" => "March","04" => "April","05" => "May","06" => "June","07" => "July","08" => "August","09" => "Septempber","10" => "October","11" => "November","12" => "December"),
                "holder" => "",
                "default" => "12",
                "desc" => "",
            ),
            "coming_days" => array(
                "title" => "Days",
                "type" => "select",
                "options" => array("00" => "00","01" => "01","02" => "02","03" => "03","04" => "04","05" => "05","06" => "06","07" => "07","08" => "08","09" => "09","10" => "10","11" => "11","12" => "12","13" => "13","14" => "14","15" => "15","16" => "16","17" => "17","18" => "18","19" => "19","20" => "20","21" => "21","22" => "22","23" => "23","24" => "24","25" => "25","26" => "26","27" => "27","28" => "28","29" => "29","30" => "30","31" => "31"),
                "holder" => "",
                "default" => "28",
                "desc" => "",
            ),
            "coming_hours" => array(
                "title" => "Hours",
                "type" => "select",
                "options" => array("00" => "00","01" => "01","02" => "02","03" => "03","04" => "04","05" => "05","06" => "06","07" => "07","08" => "08","09" => "09","10" => "10","11" => "11","12" => "12","13" => "13","14" => "14","15" => "15","16" => "16","17" => "17","18" => "18","19" => "19","20" => "20","21" => "21","22" => "22","23" => "23"),
                "holder" => "",
                "default" => "12",
                "desc" => "",
            ),
            "coming_link" => array(
                "title" => "Your Feedburner Title",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "If empty, Subscribe form none",
            ),
        ),
    ),
    "content" => array(
        "name" => "Content",
        "size" => "size-1-1",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/content-element-tutorial/",
        "settings" => array(
            "description" => array(
                "title" => "This element displays content of your Core Editor. If you want to use additional Editor Please use the Column Element on our Page builder",
                "type" => "button",
                "data" => array(),
                "default" => "",
                "desc" => "",
            ),
        ),
    ),
    "divider" => array(
        "name" => "Divider",
        "size" => "size-1-1",
        "help" => "http://support.themewaves.com/knowledgebase/divider-element-tutorial/",
        "settings" => array(
            "type" => array(
                "title" => "Choose Divider Type",
                "type" => "select",
                "options" => array("line" => "Line", "space" => "Space"),
                "default" => "line",
                "desc" => "",
            ),
            "height" => array(
                "title" => "Insert Height of the Space",
                "type" => "text",
                "holder" => "20",
                "default" => "20",
                "desc" => "",
            ),
        ),
    ),
    "dropcap" => array(
        "name" => "Dropcap",
        "only" => "shortcode", //builder
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title" => "Dropcap Text",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Insert dropcap text.",
            ),
            "color" => array(
                "title" => "Dropcap Color",
                "type" => "color",
                "holder" => "#2dcb73",
                "default" => "#2dcb73",
                "desc" => "Choose dropcap background color.",
            ),
            "style" => array(
                "title" => "Dropcap Style",
                "type" => "select",
                "options" => array("square" => "Square Flat", "circle" => "Circle Flat", "square_border" => "Square Border", "circle_border" => "Circle Border"),
                "holder" => "",
                "default" => "square",
                "desc" => "Choose dropcap text color.",
            ),
        ),
    ),
    "fontawesome" => array(
        "name" => "Font Awesome",
        "only" => "shortcode",
        "size" => "size-1-3",
        "settings" => array(
            "fa" => array(
                "title" => "Add Icon",
                "type" => "fa",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "fa_type" => array(
                "title" => "Type",
                "type" => "select",
                "holder" => "",
                "options" => array("circle" => "Circle", "square" => "square"),
                "default" => "circle",
                "desc" => "type.",
            ),
            "fa_size" => array(
                "title" => "Size",
                "type" => "hidden",
                "holder" => "",
                "default" => "30",
                "desc" => "Size.",
            ),
            "fa_padding" => array(
                "title" => "Padding",
                "type" => "hidden",
                "holder" => "",
                "default" => "20",
                "desc" => "Padding.",
            ),
            "fa_color" => array(
                "title" => "Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "#aaaaaa",
                "desc" => "Color.",
            ),
            "fa_bg_color" => array(
                "title" => "Background Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "",
                "desc" => "Background Color.",
            ),
            "fa_border_color" => array(
                "title" => "Border Color",
                "type" => "hidden",
                "holder" => "",
                "default" => "#aaaaaa",
                "desc" => "Border Color.",
            ),
            "fa_rounded" => array(
                "title" => "Border Size",
                "type" => "hidden",
                "holder" => "",
                "default" => "6",
                "desc" => "Border Size.",
            ),
            "fa_icon" => array(
                "title" => "Icon",
                "type" => "hidden",
                "holder" => "",
                "default" => "fa-angellist",
                "desc" => "Icon.",
            ),
        ),
    ),
    "label" => array(
        "name" => "Label",
        "only" => "shortcode", //builder
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title" => "Label Text",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Insert label text.",
            ),
            "color" => array(
                "title" => "Label Color",
                "type" => "color",
                "holder" => "",
                "default" => "",
                "desc" => "Choose label color.",
            ),
        ),
    ),
    "list" => array(
        "name" => "List",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/list-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "list", "settings" => "items"),
                "default" => "Add List",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "item_icon",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "title" => "",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "List Element",
                            "desc" => '',
                        ),
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "item_icon" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "fa-angellist",
                            "default" => "fa-angellist",
                            "desc" => '<a href="' . THEME_DIR . '/assets/font-awesome.html" target="_blank" title="300+ Icons list">300+ icons</a>. Copy the Icon name and paste here',
                        ),
                        "item_text" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Insert some text",
                            "default" => "Insert some text",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "map" => array(
        "name" => "Map",
        "size" => "size-1-1",
        "content" => "map_embed",
        "settings" => array(
            "type" => array(
                "title" => "Choose Layout",
                "type" => "select",
                "options" => array("boxed" => "Boxed", "full" => "Full"),
                "default" => "boxed",
                "desc" => "Choose Map type.",
            ),
            "map_embed" => array(
                "title" => "Embeded Code",
                "type" => "textArea",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
        ),
    ),
    "milestones" => array(
        "name" => "Milestones",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/milestone-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "milestones", "settings" => "items"),
                "default" => "Add Milestone",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "thumb_type" => array(
                            "title" => "Choose Thumb type",
                            "type" => "select",
                            "options" => array("image" => "Image", "fa" => "Font Awesome"),
                            "hide" => array("image" => "fa,fa_type", "fa" => "image,add_image"),
                            "default" => "fa",
                            "desc" => "Chosen type will be displayed.",
                        ),
                        // Image
                        "image" => array(
                            "title" => "Thumbnail Image",
                            "type" => "text",
                            "holder" => "",
                            "default" => "",
                            "desc" => "The preivew image.",
                        ),
                        "add_image" => array(
                            "title" => "",
                            "type" => "button",
                            "save_to" => "image",
                            "default" => "Upload",
                            "desc" => "",
                        ),
                        // Font Awesome
                        "fa" => array(
                            "title" => "Add Icon",
                            "type" => "fa",
                            "holder" => "",
                            "default" => "",
                            "desc" => "",
                        ),
                        "fa_type" => array(
                            "need_fa" => "true",
                            "title" => "Type",
                            "type" => "select",
                            "holder" => "",
                            "options" => array("circle" => "Circle", "square" => "square"),
                            "default" => "circle",
                            "desc" => "type.",
                        ),
                        "fa_size" => array(
                            "title" => "Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "25",
                            "desc" => "Size.",
                        ),
                        "fa_padding" => array(
                            "title" => "Padding",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "30",
                            "desc" => "Padding.",
                        ),
                        "fa_color" => array(
                            "title" => "Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#2dcb73",
                            "desc" => "Color.",
                        ),
                        "fa_border_color" => array(
                            "title" => "Border Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#2dcb73",
                            "desc" => "Border Color.",
                        ),
                        "fa_bg_color" => array(
                            "title" => "Background Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "",
                            "desc" => "Background Color.",
                        ),
                        "fa_border_color" => array(
                            "title" => "Border Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#2dcb73",
                            "desc" => "Border Color.",
                        ),
                        "fa_rounded" => array(
                            "title" => "Border Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "4",
                            "desc" => "Border Size.",
                        ),
                        "fa_icon" => array(
                            "title" => "Icon",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "fa-angellist",
                            "desc" => "Icon.",
                        ),
                        // -----------------------
                        "title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "Our Customers",
                            "default" => "Our Customers",
                            "desc" => "Insert your Milestone",
                        ),
                        "count" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "1500",
                            "default" => "1500",
                            "desc" => "Count Number. Note: Only Digit",
                        ),
                    ),
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "message_box" => array(
        "name" => "Message Box",
        "size" => "size-1-2",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/message-box-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "message_box", "settings" => "items"),
                "default" => "Add Message Box",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "type",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "type" => array(
                            "title" => "",
                            "type" => "select",
                            "options" => array("default" => "Default", "alert" => "Alert", "info" => "Info", "success" => "Success", "error" => "Error"),
                            "default" => "default",
                            "desc" => "",
                        ),
                        "message_content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Insert here Box Content",
                            "default" => "Insert here Box Content",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "partner" => array(
        "name" => "Partner Carousel",
        "size" => "size-1-1",
        "help" => "http://support.themewaves.com/knowledgebase/carousel/",
        "settings" => array(
            "partner_category" => array(
                "title" => "Choose Post category",
                "type" => "category",
                "options" => $partner_categories,
                "default" => "0",
                "desc" => ".",
            ),
            "partner_category_list" => array(
                "type" => "hidden",
                "selector" => "partner_category",
                "default" => "",
            ),
            "image_height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "100",
                "default" => "",
                "desc" => "Image height",
            ),
            "order" => array(
                "title" => "Order",
                "type" => "select",
                "options" => $order,
                "default" => "date_desc",
                "desc" => "",
            )
        ),
    ),
    "portfolio" => array(
        "name" => "Portfolio",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
        "help" => "http://support.themewaves.com/knowledgebase/portfolio/",
        "settings" => array(
            "port_category" => array(
                "title" => "Choose Portfolio category",
                "type" => "category",
                "options" => $port_categories,
                "default" => "0",
                "desc" => "Chosen categories will be included.",
            ),
            "category_ids" => array(
                "type" => "hidden",
                "selector" => "port_category",
                "default" => "",
            ),
            "column" => array(
                "title" => "Column count",
                "type" => "select",
                "options" => array('2' => '2 Columns', '3' => '3 Columns', '4' => '4 Columns'),
                "default" => "4",
                "desc" => "This option will only 3 Column width when you are using portfolio with Sidebar. (Not a Fullwidth layout)",
            ),
            "count" => array(
                "title" => "Count",
                "type" => "text",
                "holder" => "10",
                "default" => "10",
                "desc" => "",
            ),
            "height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "250",
                "default" => "",
                "desc" => "Portfolio item height",
            ),
            "filter" => array(
                "title" => "Display Filter?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "true",
                "desc" => "",
            ),
            "pagination" => array(
                "title" => "Display Pagination?",
                "type" => "select",
                "options" => array('none' => 'None', 'simple' => 'Simple pagination', 'infinite' => 'Infinite scroll'),
                "default" => "none",
                "desc" => "",
            ),
            "order" => array(
                "title" => "Order",
                "type" => "select",
                "options" => $order,
                "default" => "date_desc",
                "desc" => "",
            ),
            "hide_hover" => array(
                "title" => "Disable Hover Feature?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            ),
            "button_text" => array(
                "title" => "'View Large' text Change",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Empty: VIEW LARGE",
            ),
            "link_type" => array(
                "title" => "Link Open Type?",
                "type" => "select",
                "options" => array('view_large'=>'View large','permalink'=>'Permalink','preview_url'=>'Preview URL'),
                "default" => "view_large",
                "desc" => "Preview Url is located in Portfolio Single",
            ),
            "hide_favorites" => array(
                "title" => "Disable Favorite?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            )
        ),
    ),
    "recent_portfolios" => array(
        "name" => "Portfolio Carousel",
        "size" => "size-1-1",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/carousel/",
        "settings" => array(
            "port_category" => array(
                "title" => "Portfolio category",
                "type" => "category",
                "options" => $port_categories,
                "default" => "0",
                "desc" => "Chosen categories will be included.",
            ),
            "port_category_list" => array(
                "type" => "hidden",
                "selector" => "port_category",
                "default" => "",
            ),
            "post_count" => array(
                "title" => "Post Count",
                "type" => "text",
                "holder" => "10",
                "default" => "6",
                "desc" => "Insert how many posts will displayed.",
            ),
            "image_height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "250",
                "default" => "",
                "desc" => "Image height",
            ),
            "order" => array(
                "title" => "Order",
                "type" => "select",
                "options" => $order,
                "default" => "date_desc",
                "desc" => "",
            ),
            "description_title" => array(
                "title" => "Description Title",
                "type" => "text",
                "holder" => "Title",
                "default" => "",
                "desc" => "",
            ),
            "description_text" => array(
                "title" => "Description Text",
                "type" => "textArea",
                "holder" => "Description text",
                "default" => "",
                "desc" => "",
            ),            
            "hide_hover" => array(
                "title" => "Disable Hover Feature?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            ),
            "button_text" => array(
                "title" => "'View Large' text Change",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Empty: VIEW LARGE",
            ),
            "link_type" => array(
                "title" => "Link Open Type?",
                "type" => "select",
                "options" => array('view_large'=>'View large','permalink'=>'Permalink','preview_url'=>'Preview URL'),
                "default" => "view_large",
                "desc" => "Preview Url is located in Portfolio Single",
            ),
            "hide_favorites" => array(
                "title" => "Disable Favorite?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            )
        ),
    ),
    "recent_posts" => array(
        "name" => "Post Carousel",
        "size" => "size-1-1",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/carousel/",
        "settings" => array(
            "post_category" => array(
                "title" => "Choose Post category",
                "type" => "category",
                "options" => $post_categories,
                "default" => "0",
                "desc" => ".",
            ),
            "post_category_list" => array(
                "type" => "hidden",
                "selector" => "post_category",
                "default" => "",
            ),
            "post_count" => array(
                "title" => "Post Count",
                "type" => "text",
                "holder" => "10",
                "default" => "6",
                "desc" => "Insert how many posts will displayed.",
            ),
            "excerpt_count" => array(
                "title" => "Excerpt Count",
                "type" => "text",
                "holder" => "50",
                "default" => "50",
                "desc" => "How much blog words displayed in blog Excerpt. Must insert Digits including 0.",
            ),
            "more_text_show" => array(
                "title" => "Read more",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "Enable or Disable more text.",
            ),
            "more_text" => array(
                "title" => "Read more text",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Insert custom 'Read More' text",
            ),
            "image_height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "250",
                "default" => "",
                "desc" => "Image height",
            ),
            "order" => array(
                "title" => "Order",
                "type" => "select",
                "options" => $order,
                "default" => "date_desc",
                "desc" => "",
            ),
            "hide_hover" => array(
                "title" => "Disable Hover Feature?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            ),
            "button_text" => array(
                "title" => "'View Large' text Change",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "Empty: VIEW LARGE",
            ),
            "link_type" => array(
                "title" => "Link Open Type?",
                "type" => "select",
                "options" => array('view_large'=>'View large','permalink'=>'Permalink'),
                "default" => "view_large",
                "desc" => "Preview Url is located in Portfolio Single",
            ),
            "hide_meta" => array(
                "title" => "Disable Meta?",
                "type" => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc" => "",
            )
        ),
    ),
    "php" => array(
        "name" => "PHP",
        "size" => "size-1-3",
        "only" => "builder",
        "content" => "php_content",
        "settings" => array(
            "php_content" => array(
                "title"   => "",
                "type"    => "textArea",
                "holder"  => "",
                "default" => "",
                "desc"    => "",
            ),
        ),
    ),
    "pricing_table" => array(
        "name" => "Pricing Table",
        "size" => "size-1-1",
        "min-size" => "size-1-2",
        "help" => "http://support.themewaves.com/knowledgebase/pricing-table-element-tutorial/",
        "settings" => array(
            "column" => array(
                "title" => "Choose the Pricing Tables Column",
                "type" => "select",
                "options" => array("2" => "2 Columns", "3" => "3 Columns", "4" => "4 Columns", "5" => "5 Columns"),
                "default" => "2",
                "desc" => "",
            ),
            "price_category" => array(
                "title" => "Pricing Table category",
                "type" => "category",
                "options" => $price_categories,
                "default" => "0",
                "desc" => "Choose the Pricing Table category you want to include.",
            ),
            "price_category_list" => array(
                "type" => "hidden",
                "selector" => "price_category",
                "default" => "",
            ),
        ),
    ),
    "progress" => array(
        "name" => "Progress Bar",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/progress-bar-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "progress", "settings" => "items"),
                "default" => "Add Progress Bar",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "progress_title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "progress_title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "Progress title",
                            "default" => "Progress title",
                            "desc" => "",
                        ),
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "percent" => array(
                            "title" => "Progress Percent",
                            "type" => "text",
                            "holder" => "Progress percent",
                            "default" => "50",
                            "desc" => "integer value in 0-100.",
                        ),
                        "type" => array(
                            "title" => "Choose Type",
                            "type" => "select",
                            "options" => array("default" => "Default", "striped" => "Striped", "animated" => "Animated"),
                            "desc" => "Choose Type",
                        ),
                        "color" => array(
                            "title" => "Color of Progress",
                            "type" => "color",
                            "holder" => "Color of Progress",
                            "default" => "#2dcb73",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "service" => array(
        "name" => "Service",
        "size" => "size-1-3",
        "help" => "http://support.themewaves.com/knowledgebase/service-element-tutorial/",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "service", "settings" => "items"),
                "default" => "Add Service",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "service_style" => array(
                            "title" => "",
                            "type" => "select",
                            "options" => array('style_1' => 'Icon + Title + Desc', 'style_2' => 'Icon(FL) + Title + Desc'),
                            "default" => "style_1",
                            "desc" => "FL means Icons Floated Left, FR means Icons Floated Right.",
                        ),
                        "thumb_type" => array(
                            "title" => "Choose Thumb type",
                            "type" => "select",
                            "options" => array("image" => "Image", "fa" => "Font Awesome", "cc" => "Circle Chart"),
                            "hide" => array("image" => "fa,fa_type,cc", "fa" => "service_thumb,add_thumb,service_thumb_height,service_thumb_width,fa_type,cc", "cc" => "service_thumb,add_thumb,service_thumb_height,service_thumb_width,fa_type,fa"),
                            "default" => "fa",
                            "desc" => "Chosen Post type will be displayed.",
                        ),
                        "service_thumb_width" => array(
                            "title" => "Service Thumbnail Image Width",
                            "type" => "text",
                            "holder" => "",
                            "default" => "20",
                            "desc" => "The preivew image width.",
                        ),
                        "service_thumb" => array(
                            "title" => "Service Thumbnail Image",
                            "type" => "text",
                            "holder" => "",
                            "default" => "",
                            "desc" => "The preivew image.",
                        ),
                        "add_thumb" => array(
                            "title" => "",
                            "type" => "button",
                            "save_to" => "service_thumb",
                            "default" => "Upload",
                            "desc" => "",
                        ),
                        // Font Awesome
                        "fa" => array(
                            "title" => "Add Icon",
                            "type" => "fa",
                            "holder" => "",
                            "default" => "",
                            "desc" => "",
                        ),
                        "fa_type" => array(
                            "need_fa" => "true",
                            "title" => "Type",
                            "type" => "select",
                            "holder" => "",
                            "options" => array("circle" => "Circle", "square" => "square"),
                            "default" => "circle",
                            "desc" => "type.",
                        ),
                        "fa_size" => array(
                            "title" => "Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "30",
                            "desc" => "Size.",
                        ),
                        "fa_padding" => array(
                            "title" => "Padding",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "20",
                            "desc" => "Padding.",
                        ),
                        "fa_color" => array(
                            "title" => "Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#aaaaaa",
                            "desc" => "Color.",
                        ),
                        "fa_bg_color" => array(
                            "title" => "Background Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "",
                            "desc" => "Background Color.",
                        ),
                        "fa_border_color" => array(
                            "title" => "Border Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#aaaaaa",
                            "desc" => "Border Color.",
                        ),
                        "fa_rounded" => array(
                            "title" => "Border Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "6",
                            "desc" => "Border Size.",
                        ),
                        "fa_icon" => array(
                            "title" => "Icon",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "fa-angellist",
                            "desc" => "Icon.",
                        ),
                        // Circle Chart
                        "cc" => array(
                            "title" => "Add Chart",
                            "type" => "cc",
                            "holder" => "",
                            "default" => "",
                            "desc" => "",
                        ),
                        "cc_type" => array(
                            "need_cc" => "true",
                            "title" => "Type",
                            "type" => "select",
                            "options" => array('text' => 'Text', 'fa' => 'Font Awesome'),
                            "default" => "text",
                            "desc" => "",
                        ),
                        "cc_line_width" => array(
                            "title" => "Line Width",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "8",
                            "desc" => "",
                        ),
                        "cc_text" => array(
                            "title" => "Text",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "80%",
                            "desc" => "",
                        ),
                        "cc_percent" => array(
                            "title" => "Percent",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "80",
                            "desc" => "",
                        ),
                        "cc_size" => array(
                            "title" => "Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "100",
                            "desc" => "",
                        ),
                        "cc_font_size" => array(
                            "title" => "Font Size",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "30",
                            "desc" => "",
                        ),
                        "cc_font_color" => array(
                            "title" => "Font Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#2dcb73",
                            "desc" => "",
                        ),
                        "cc_color" => array(
                            "title" => "Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#2dcb73",
                            "desc" => "",
                        ),
                        "cc_track_color" => array(
                            "title" => "Track Color",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "#f9f9f9",
                            "desc" => "",
                        ),
                        "cc_icon" => array(
                            "title" => "Icon",
                            "type" => "hidden",
                            "holder" => "",
                            "default" => "fa-angellist",
                            "desc" => "",
                        ),
                        // -----------------------
                        "title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "Your Service Title",
                            "default" => "Your Service Title",
                            "desc" => "",
                        ),
                        "content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Column Content",
                            "default" => "Column Content",
                            "desc" => "",
                        ),
                        "more_text" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "Read More",
                            "default" => "Read More",
                            "desc" => "Insert Custom Read More text",
                        ),
                        "more_url" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "Only URL here",
                            "default" => "",
                            "desc" => "Read More URL.",
                        ),
                        "more_target" => array(
                            "title" => "",
                            "type" => "select",
                            "options" => $linkTarget,
                            "default" => "_blank",
                            "desc" => "Blank is opened new windows. Self will current.",
                        ),
                    ),
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "sidebar" => array(
        "name" => "Sidebar",
        "size" => "size-1-4",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/sidebar-element-tutorial/",
        "settings" => array(
            "name" => array(
                "title" => "",
                "type" => "select",
                "options" => $arraySidebar,
                "default" => "Default sidebar",
                "desc" => "Please creat your own Sidebar in Theme Options Sidebar Creater then Choose here.",
            ),
        ),
    ),
    "slider" => array(
        "name" => "Slider",
        "size" => "size-1-1",
        "filter"  => "",
        "content" => "items,slider",
        "help" => "http://support.themewaves.com/knowledgebase/accordion-element-tutorial/",
        "settings" => array(
            "slider_type" => array(
                "title"   => "Choose the Slider Type",
                "type"    => "select",
                "options" => array(
                    'masterslider'=>'Master Slider',
                    'layerslider' =>'Layer Slider',
                    'revslider'   =>'Rev Slider',
                ),
                "hide"    => array("masterslider" => "layerslider_id,revslider_id","layerslider" => "revslider_id,masterslider_id", "revslider" => "layerslider_id,masterslider_id"),
                "default" => "masterslider",
                "desc"    => "",
            ),
            "masterslider_id" => array(
                "title"   => "Choose the Slider",
                "type"    => "select",
                "options" => $waves_element_options['masterslider'],
                "default" => "0",
                "desc"    => "Your created Sliders will be displayed here. Including LayersSlider and all of our used sliders.",
            ),
            "layerslider_id" => array(
                "title"   => "Choose the Slider",
                "type"    => "select",
                "options" => $waves_element_options['layerslider'],
                "default" => "0",
                "desc"    => "Your created Sliders will be displayed here. Including LayersSlider and all of our used sliders.",
            ),
            "revslider_id" => array(
                "title"   => "Choose the Slider",
                "type"    => "select",
                "options" => $waves_element_options['revslider'],
                "default" => "0",
                "desc"    => "Your created Sliders will be displayed here. Including LayersSlider and all of our used sliders.",
            ),
        ),
    ),
    "tab" => array(
        "name" => "Tab",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/tab-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "tab", "settings" => "items"),
                "default" => "Add Tab",
                "desc" => "",
            ),
            "position" => array(
                "title" => "Choose Tab position",
                "type" => "select",
                "options" => array("top" => "Top", "left" => "Left", "right" => "Right"),
                "default" => "top",
                "desc" => "Tab Titles can be displayed top, right, left position.",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "",
                            "default" => "Tab Title",
                            "desc" => "",
                        ),
                        "title_icon" => array(
                            "title" => "Icon code here",
                            "type" => "text",
                            "holder" => "fa-angellist",
                            "default" => "fa-angellist",
                            "desc" => '<a href="' . THEME_DIR . '/assets/font-awesome.html" target="_blank" title="300+ Icons list">300+ icons</a>. Copy the Icon name and paste here',
                        ),
                        "item_content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Tab Content",
                            "default" => "Tab Content",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "team" => array(
        "name" => "Team",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
        "only" => "builder",
        "help" => "http://support.themewaves.com/knowledgebase/team-element-tutorial//",
        "settings" => array(
            "team_category" => array(
                "title" => "Choose Team category",
                "type" => "category",
                "options" => $team_categories,
                "default" => "0",
                "desc" => "Chosen categories will be displayed.",
            ),
            "category_ids" => array(
                "type" => "hidden",
                "selector" => "team_category",
                "default" => "",
            ),
            "height" => array(
                "title" => "Height",
                "type" => "text",
                "holder" => "250",
                "default" => "250",
                "desc" => "image height (px)",
            ),
            "count" => array(
                "title" => "Count",
                "type" => "text",
                "holder" => "4",
                "default" => "4",
                "desc" => "",
            ),
        ),
    ),
    "testimonials" => array(
        "name" => "Testimonials",
        "size" => "size-1-2",
        "help" => "http://support.themewaves.com/knowledgebase/testimonial-element-tutorial/",
        "settings" => array(
            "testim_category" => array(
                "title" => "",
                "type" => "category",
                "options" => $testim_categories,
                "default" => "0",
                "desc" => "Chosen categories will be displayed.",
            ),
            "category_ids" => array(
                "type" => "hidden",
                "selector" => "testim_category",
                "default" => "",
            ),
            "count" => array(
                "title" => "Count",
                "type" => "text",
                "holder" => "5",
                "default" => "5",
                "desc" => "",
            ),
            "bg_color" => array(
                "title" => "Background color",
                "type" => "color",
                "default" => "",
            ),
            "text_color" => array(
                "title" => "Text color",
                "type" => "color",
                "default" => "",
            ),
            "name_color" => array(
                "title" => "Author name color",
                "type" => "color",
                "default" => "",
            ),
            "direction" => array(
                "title" => "Choose Testimonials direction",
                "type" => "select",
                "options" => array("up" => "UP", "down" => "DOWN", "left" => "LEFT", "right" => "RIGHT"),
                "default" => "up",
                "desc" => "Chosen direction.",
            ),
            "duration" => array(
                "title" => "Duration",
                "type" => "text",
                "holder" => "1000",
                "default" => "1000",
                "desc" => "",
            ),
            "timeout" => array(
                "title" => "timeout",
                "type" => "text",
                "holder" => "2000",
                "default" => "2000",
                "desc" => "",
            ),
        ),
    ),
    "toggle" => array(
        "name" => "Toggle",
        "size" => "size-1-3",
        "content" => "items",
        "help" => "http://support.themewaves.com/knowledgebase/toggle-element-tutorial/",
        "settings" => array(
            "add_item" => array(
                "title" => "",
                "type" => "button",
                "data" => array("item" => "toggle", "settings" => "items"),
                "default" => "Add Toggle",
                "desc" => "",
            ),
            "items" => array(
                "title" => "Items",
                "type" => "container",
                "container_type" => "toggle",
                "title_as" => "item_title",
                "add_button" => "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "title" => "",
                            "type" => "text",
                            "holder" => "",
                            "default" => "Toggle Title",
                            "desc" => "",
                        ),
                        "item_animation" => array(
                            "title" => "Animation",
                            "type" => "select",
                            "options" => $genAnimationArray,
                            "default" => "none",
                            "desc" => "Animation.",
                        ),
                        "item_animation_delay" => array(
                            "title" => "Animation delay",
                            "type" => "text",
                            "holder" => "Example:300",
                            "default" => "",
                            "desc" => "Animation Delay",
                        ),
                        "color" => array(
                            "title" => "Color",
                            "type" => "color",
                            "holder" => "#2dcb73",
                            "default" => "#2dcb73",
                            "desc" => "Choose color.",
                        ),
                        "item_expand" => array(
                            "title" => "Expand?",
                            "type" => "checkbox",
                            "default" => "false",
                            "desc" => "",
                        ),
                        "item_content" => array(
                            "title" => "",
                            "type" => "textArea",
                            "holder" => "Toggle Content",
                            "default" => "Toggle Content",
                            "desc" => "",
                        ),
                    )
                ),
                "desc" => "Items",
            ),
        ),
    ),
    "twitter" => array(
        "name" => "Twitter",
        "size" => "size-1-3",
        "help" => "http://support.themewaves.com/knowledgebase/twitter-element-tutorial/",
        "settings" => array(
            "username" => array(
                "title" => "Insert Twitter Username",
                "type" => "text",
                "holder" => "",
                "default" => "themewaves",
                "desc" => "Only twitter username.",
            ),
            "tweetstoshow" => array(
                "title" => "Count",
                "type" => "select",
                "options" => array("1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6", "7" => "7", "8" => "8", "9" => "9", "10" => "10"),
                "default" => "3",
                "desc" => "",
            ),
            "cachetime" => array(
                "title" => "Cache Tweets in every * hours",
                "type" => "text",
                "holder" => "",
                "default" => "1",
                "desc" => "",
            ),
        ),
    ),
    "twitter_carousel" => array(
        "name" => "Twitter Carousel",
        "size" => "size-1-1",
        "help" => "http://support.themewaves.com/knowledgebase/twitter-carousel-element-tutorial/",
        "settings" => array(
            "username" => array(
                "title" => "Insert Twitter Username",
                "type" => "text",
                "holder" => "",
                "default" => "themewaves",
                "desc" => "Only twitter username.",
            ),
            "tweetstoshow" => array(
                "title" => "Count",
                "type" => "select",
                "options" => array("1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6", "7" => "7", "8" => "8", "9" => "9", "10" => "10"),
                "default" => "3",
                "desc" => "",
            ),
            "cachetime" => array(
                "title" => "Cache Tweets in every * hours",
                "type" => "text",
                "holder" => "",
                "default" => "1",
                "desc" => "",
            ),
        ),
    ),
    "video" => array(
        "name" => "Video",
        "size" => "size-1-1",
        "content" => "video_embed",
        "help" => "http://support.themewaves.com/knowledgebase/video/",
        "settings" => array(
            "insert_type" => array(
                "title" => "Choose Post type",
                "type" => "select",
                "options" => array("type_bg" => "Background", "type_url" => "URL", "type_embed" => "Embed"),
                "hide" => array("type_url" => "video_embed,video_text", "type_embed" => "video_m4v,add_video,video_thumb,add_thumb,video_text", "type_bg" => "video_m4v,add_video,video_thumb,add_thumb,video_embed"),
                "default" => "type_bg",
                "desc" => "Chosen Post type will be displayed.",
            ),
            "video_text" => array(
                "title" => "Video Text",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
            "video_m4v" => array(
                "title" => "M4V File URL",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "The URL to the .m4v video file.",
            ),
            "add_video" => array(
                "title" => "",
                "type" => "button",
                "save_to" => "video_m4v",
                "default" => "Upload",
                "desc" => "",
            ),
            "video_thumb" => array(
                "title" => "Video Thumbnail Image",
                "type" => "text",
                "holder" => "",
                "default" => "",
                "desc" => "The preivew image.",
            ),
            "add_thumb" => array(
                "title" => "",
                "type" => "button",
                "save_to" => "video_thumb",
                "default" => "Upload",
                "desc" => "",
            ),
            "video_embed" => array(
                "title" => "Embeded Code",
                "type" => "textArea",
                "holder" => "",
                "default" => "",
                "desc" => "",
            ),
        ),
    ),
);
?>